config/routes.rb
Rails.application.routes.draw do
  # get 'user/show'

  get 'static/home'
  root 'static#home'

  # get 'users/:user_id/links/:id', to: 'links#show'

  resources :list_tasks
  resources :tasks
  resources :lists
  resources :user_videos
  resources :videos
  resources :user_links
  resources :links
  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :links
  end

  resources :users do
    resources :lists
  end

  resources :users do
    resources :videos
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord

  belongs_to :user
  has_many :list_tasks
  has_many :tasks, through: :list_tasks
  validates :title, presence: true

  def tasks_attributes=(attr)
    # binding.pry
    attr[:list][:tasks_attributes].each do |k, v|
      if !v.values.nil? && v.values != ""
        t = Task.find_or_create_by(description: v.values[0])
        z = ListTask.create(list_id: self.id, task_id: t.id, expiration: attr[:list][:list_task][:expiration].to_i)
      end
    end
    # attr
    # if !attr[:list][:tasks_attributes]["0"].nil?
    #   t = Task.find_or_create_by(description: attr[:list][:tasks_attributes]["0"][:description])
    #   lt = ListTask.create(list_id: self.id, task_id: t.id, expiration: attr[:list][:list_task][:expiration].to_i)
    # end
    # if !attr[:list][:tasks_attributes]["1"].nil?
    #   z = Task.find_or_create_by(description: attr[:list][:tasks_attributes]["1"][:description])
    #   lz = ListTask.create(list_id: self.id, task_id: z.id, expiration: attr[:list][:list_task][:expiration].to_i)
    # end
    # if !attr[:list][:tasks_attributes]["2"].nil?
    #   y = Task.find_or_create_by(description: attr[:list][:tasks_attributes]["2"][:description])
    #   ly = ListTask.create(list_id: self.id, task_id: y.id, expiration: attr[:list][:list_task][:expiration].to_i)
    # end
    # self.tasks.build(attr)
  end

  # def list_tasks_attributes=(attr)
  #   binding.pry
  #   # self.list_tasks[-1].expiration = attr[:expiration]
  # end
end


  # def tasks_attributes=(attr)
  #
  # end




# class List < ApplicationRecord
#
#   belongs_to :user
#   has_many :list_tasks
#   has_many :tasks, through: :list_tasks
#   validates :title, presence: true
#
#   def tasks_attributes=(attributes)
#     binding.pry
#     # build_task_and_list_task(attr[:list][:tasks_attributes]["0"]) if
#     # build_task_and_list_task(attr[:list][:tasks_attributes]["1"])
#     # build_task_and_list_task(attr[:list][:tasks_attributes]["2"])
#
#     # attributes.each do |attr|
#     #   build_task_and_list_task(attr) if !attr.nil?
#     # end
#     if !attr[:list][:tasks_attributes]["0"].nil?
#       t = Task.find_or_create_by(description: attr[:list][:tasks_attributes]["0"][:description])
#       lt = ListTask.create(list_id: self.id, task_id: t.id, expiration: attr[:list][:list_task][:expiration].to_i)
#     end
#     if !attr[:list][:tasks_attributes]["1"].nil?
#       z = Task.find_or_create_by(description: attr[:list][:tasks_attributes]["1"][:description])
#       lz = ListTask.create(list_id: self.id, task_id: z.id, expiration: attr[:list][:list_task][:expiration].to_i)
#     end
#     if !attr[:list][:tasks_attributes]["2"].nil?
#       y = Task.find_or_create_by(description: attr[:list][:tasks_attributes]["2"][:description])
#       ly = ListTask.create(list_id: self.id, task_id: y.id, expiration: attr[:list][:list_task][:expiration].to_i)
#     end
#     # self.tasks.build(attr)
#
#     # def build_task_and_list_task(attr)
#     #   y = Task.find_or_create_by(description: attr[:list][:tasks_attributes][:description])
#     #   ly = ListTask.create(list_id: self.id, task_id: y.id, expiration: attr[:list][:list_task][:expiration].to_i)
#     # end
#   end
#
#   # def list_tasks_attributes=(attr)
#   #   binding.pry
#   #   # self.list_tasks[-1].expiration = attr[:expiration]
#   # end
#
# end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
    @list.tasks.build
    @tasks = Task.all
  end

  def create
    # binding.pry
    # list = List.create(list_params)
    if params[:list][:list_task][:expiration].to_i < 4 && params[:list][:list_task][:expiration].to_i > 0
      # list = List.create(user_id: current_user.id, title: params[:list][:title])
      list = current_user.lists.build(title: params[:list][:title])
      list.save
      list.tasks_attributes=(params)
      # binding.pry
      redirect_to list_path(list)
    else
      redirect_to new_list_path
    end
  end

  def show
    @list = List.find_by(id: params[:id])
    # binding.pry
  end

  def destroy
    list = List.find_by(id: params[:id])
    list.destroy
    redirect_to '/'
  end

  def edit
    @list = List.find_by(id: params[:id])
    # @list_id = params[:id]
    # @new_list = List.new
    # print @list.user
    # print @list.tasks.map { |t| t.description }
    # @new_list.tasks.build
    # puts @list.tasks
  end

  def update
    @list = List.find_by(id: params[:id])
    # list.tasks_attributes=(params)
    # binding.pry
    if !params[:list][:new_task_1][:description].empty?
      t = Task.find_or_create_by(description: params[:list][:new_task_1][:description])
      lt = ListTask.create(list_id: @list.id, task_id: t.id, expiration: params[:list][:list_task][:expiration].to_i)
    end
    if !params[:list][:new_task_2][:description].empty?
      y = Task.find_or_create_by(description: params[:list][:new_task_2][:description])
      ly = ListTask.create(list_id: @list.id, task_id: y.id, expiration: params[:list][:list_task][:expiration].to_i)
    end
    if !params[:list][:new_task_3][:description].empty?
      z = Task.find_or_create_by(description: params[:list][:new_task_3][:description])
      lz = ListTask.create(list_id: @list.id, task_id: z.id, expiration: params[:list][:list_task][:expiration].to_i)
    end
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:title, tasks_attributes:[:description], list_task:[:expiration])
  end

  #
  # def list_params
  #   params.require(:list).permit(:title)
  # end

  # def list_params(*args)
  #   params.require(:list).permit(:title, :tasks_attributes)
  # end

end






# class ListsController < ApplicationController
#
#   def new
#     @list = List.new
#     @list.tasks.build
#     @tasks = Task.all
#   end
#
#   def create
#     binding.pry
#     # list = List.create(list_params)
#     if params[:list][:list_task][:expiration].to_i < 4 && params[:list][:list_task][:expiration].to_i > 0
#       # binding.pry
#       # list = List.create(user_id: current_user.id, title: params[:list][:title])
#       info = list_params
#       info[:tasks_attributes].each do |t_a|
#         t_a[:expiration] = params[:list][:list_task][:expiration]
#       end
#
#       current_user.lists.create(info)
#       # binding.pry
#       # list.tasks_attributes=(params)
#       # list.update(list_params)
#       # binding.pry
#       redirect_to list_path(list)
#     else
#       redirect_to new_list_path
#     end
#   end
#
#   def show
#     @list = List.find_by(id: params[:id])
#     # binding.pry
#   end
#
#   def destroy
#     list = List.find_by(id: params[:id])
#     list.destroy
#     redirect_to '/'
#   end
#
#   def edit
#     @list = List.find_by(id: params[:id])
#     @list.tasks.build
#   end
#
#   def update
#     @list = List.find_by(id: params[:id])
#     # list.tasks_attributes=(params)
#     # binding.pry
#     if !params[:list][:new_task_1][:description].empty?
#       t = Task.find_or_create_by(description: params[:list][:new_task_1][:description])
#       lt = ListTask.create(list_id: @list.id, task_id: t.id, expiration: params[:list][:list_task][:expiration].to_i)
#     end
#     if !params[:list][:new_task_2][:description].empty?
#       y = Task.find_or_create_by(description: params[:list][:new_task_2][:description])
#       ly = ListTask.create(list_id: @list.id, task_id: y.id, expiration: params[:list][:list_task][:expiration].to_i)
#     end
#     if !params[:list][:new_task_3][:description].empty?
#       z = Task.find_or_create_by(description: params[:list][:new_task_3][:description])
#       lz = ListTask.create(list_id: @list.id, task_id: z.id, expiration: params[:list][:list_task][:expiration].to_i)
#     end
#     redirect_to list_path(@list)
#   end
#
#   private
#   #
#   def list_params
#     params.require(:list).permit(:title, tasks_attributes:[:description], list_task:[:expiration])
#   end
#
#   # def list_params(*args)
#   #   params.require(:list).permit(:title, :tasks_attributes)
#   # end
#
# end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<br>
<h5>Add your tasks below.</h5>
<div class="field"><%= f.label :name, "Add this task." %><br>
   <%= f.fields_for :tasks do |task| %>
    <%= task.label :description %>
    <%= task.text_area :description %><br>
    <% end %>
    </div>
<br>

<div class="field"><%= f.label :name, "Add this task." %><br>
   <%= f.fields_for :tasks do |task| %>
    <%= task.label :description %>
    <%= task.text_area :description %><br>
    <% end %>
    </div>
<br>

<div class="field"><%= f.label :name, "Add this task." %><br>
   <%= f.fields_for :tasks do |task| %>
    <%= task.label :description %>
    <%= task.text_area :description %><br>
    <% end %>
    </div>
<br>

<%= f.fields_for :list_task do |l| %>
 <%= l.label "Enter 1-3 as the number of weeks you'd like these tasks available for." %>
 <%= l.number_field :expiration %><br>
<% end %>
<br>

<%= f.submit "Submit List" %>

app/views/lists/edit.html.erb
<h3>Add some tasks to <%=@list.title%> here...</h3>

<%= form_for @list do |f| %>

  <% if @list.tasks.empty? %>
    <h3>This list currently has no tasks.</h3>
  <% else %>
    <h3>Here are the current tasks on this list:</h3><br>
    <%@list.tasks.each do |t| %>
      <%= t.description %><br>
    <% end %>
  <% end %>

  <h5>Add your new tasks below.</h5>
  <br>
  <%= f.fields_for :new_task_1 do |task| %>
    <%= task.label :description %>
    <%= task.text_area :description %><br>
  <% end %>
  <br>
  <%= f.fields_for :new_task_2 do |task| %>
    <%= task.label :description %>
    <%= task.text_area :description %><br>
  <% end %>
  <br>
  <%= f.fields_for :new_task_3 do |task| %>
    <%= task.label :description %>
    <%= task.text_area :description %><br>
  <% end %>
  <br>


  <%= f.fields_for :list_task do |l| %>
   <%= l.label "Enter 1-3 as the number of weeks you'd like these tasks available for." %>
   <%= l.number_field :expiration %><br>
  <% end %><br>

  <%= f.submit "Submit List" %>

<% end %>

app/views/lists/new.html.erb
<h3>Create your new list here...</h3>

<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= render partial: "lists/form", :locals=>{:f=>f} %>

<% end %>

app/views/lists/show.html.erb
<h2><%= @list.title %></h2>
<br>
<% @list.list_tasks.each do |lt| %>
<h4><%= lt.task.description %></h4>
<%= link_to("Mark this task finished.", list_task_path(lt), :data => { :confirm => "Are you sure you completed it?" }, :method => :delete, :class => 'button-xs') %>
<br>
<h3>This task will expire on <%=lt.expiration_date%>. <%=lt.time_left%></h3>
<% end %>
<br>
<%= link_to "Add tasks to this list here.", edit_list_path(@list) %>
<br>
<%= link_to("You can also delete this list by clicking here.", list_path(@list), :data => { :confirm => "Are you sure you're finished with this list?" }, :method => :delete, :class => 'button-xs') %>