config/routes.rb
Rails.application.routes.draw do
  # get 'user/show'

  get 'static/home'
  root 'static#home'

  # get 'users/:user_id/links/:id', to: 'links#show'

  resources :list_tasks
  resources :tasks
  resources :lists
  resources :user_videos
  resources :videos
  resources :user_links
  resources :links
  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :links
  end

  resources :users do
    resources :lists
  end

  resources :users do
    resources :videos
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord

  has_many :user_videos
  has_many :users, through: :user_videos
  validates :description, presence: true
  validates :link, presence: true

  def self.top
    a = nil
    Video.all.each do |l|
      # binding.pry
      if a == nil
        a = l
      elsif l.user_videos.count > a.user_videos.count
        a = l
      end
    end
    a
  end


end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def new
    @video = Video.new
  end

  def create
    # binding.pry
    @video = Video.find_or_create_by(video_params)
    if @video.valid?
      # video.description = params[:video][:description]
      # video.link = params[:video][:link]
      # video.save
      u_vid = UserVideo.new(user_id: current_user.id, video_id: @video.id, expiration: params[:video][:user_video][:expiration].to_i)
      if u_vid.save
        redirect_to video_path(@video)
      else
        @video = Video.new
        render :new
      end
    else
      render :new
    end
  end

  def show
    @video = Video.find_by(id: params[:id])
    @user_video = UserVideo.where(user_id: current_user.id, video_id: @video.id)[0]
    # binding.pry

  end

  def index
    @videos = Video.all
  end

  def destroy

  end

  private

  def video_params
    params.require(:video).permit(:description, :link)
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<% @videos.each do |v| %>
<br>
<h3>--------------------</h3>
<li><h3><%= link_to v.description, video_path(v) %></h3></li>
<h3>Here are users who are saving this video:</h3>
<% v.users.each do |u| %>
<li><%= u.email %></li>
<% end %>
<h3>--------------------</h3>
<% end %>

app/views/videos/new.html.erb
<h3>Add your new video!</h3>

<%= form_for @video do |f| %>
<% if @video.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
<%= f.label :description %>
<br>
<%= f.text_field :description %>
<br>
<%= f.label "Link, please use only the SRC of an embed link!" %>
<br>
<%= f.text_field :link %>
<br>
<%= f.fields_for :user_video do |v| %>
 <%= v.label "Enter 1-3 as the number of weeks you'd like your video available for." %>
 <br>
 <%= v.number_field :expiration %><br>
<% end %>
<br>
<%= f.submit "Submit Video" %>
<% end %>

app/views/videos/show.html.erb
<%= @video.description %>
<br>
<iframe width="560" height="315" src="<%=@video.link%>" frameborder="0" allowfullscreen></iframe>
<br>
<% if @user_video != nil %>
<h3>This video will expire on <%=@user_video.expiration_date%>. <%=@user_video.time_left%></h3>
<br>
<%= link_to("Mark this video watched.", user_video_path(@user_video), :data => { :confirm => "Are you sure you watched it?" }, :method => :delete, :class => 'button-xs')%>
<% end %>