config/routes.rb
Rails.application.routes.draw do
  # get 'user/show'

  get 'static/home'
  root 'static#home'

  # get 'users/:user_id/links/:id', to: 'links#show'

  resources :list_tasks
  resources :tasks
  resources :lists
  resources :user_videos
  resources :videos
  resources :user_links
  resources :links
  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :links
  end

  resources :users do
    resources :lists
  end

  resources :users do
    resources :videos
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/link.rb
class Link < ApplicationRecord

  has_many :user_links
  has_many :users, through: :user_links
  validates :title, presence: true
  validates :description, presence: true
  validates :link, presence: true



  def self.top
    a = nil
    Link.all.each do |l|
      # binding.pry
      if a == nil
        a = l
      elsif l.user_links.count > a.user_links.count
        a = l
      end
    end
    a
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @link = Link.new
  end

  def create
    # find or create
    # binding.pry
    @link = Link.find_or_create_by(link_params)
      if @link.valid?
      # link = Link.new
      # link.title = params[:link][:title]
      # link.description = params[:link][:description]
      # link.link = params[:link][:link]
      # link.save
      # link.user_links.build(expiration_params.merge({user_id: current_user.id}))
      # binding.pry
        u_link = UserLink.new(user_id: current_user.id, link_id: @link.id, expiration: params[:link][:user_link][:expiration].to_i)
        if u_link.save
          redirect_to link_path(@link)
        else
          @link = Link.new
          render :new
        end
      else
        render :new
      end
  end

  def show
    if current_user.id != params[:user_id]
      flash[:message] = "Not your page."
      redirect_to '/'
    else
      @link = Link.find_by(id: params[:id])
      @user_link = UserLink.where(user_id: current_user.id, link_id: @link.id)[0]
    end

  end

  def index
    @links = Link.all
  end

  private

  def link_params
    params.require(:link).permit(:title, :description, :link)
  end

  # def expiration_params
  #   # params.require(:link).permit(:user_link =>[:expiration])
  # end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/index.html.erb
<% @links.each do |v| %>
<br>
<h3>--------------------</h3>
<li><h3><%= link_to v.title, link_path(v) %></h3></li>
<h3>Here are users who are saving this link:</h3>
<% v.users.each do |u| %>
<li><%= u.email %></li>
<% end %>
<h3>--------------------</h3>
<% end %>

app/views/links/new.html.erb
<h3>I hope you get to read this link in time.</h3>
<%= form_for @link do |f| %>
<% if @link.errors.any? %>

<div id="error_explanation">
  <h2>There were some errors:</h2>
  <ul>
    <% @link.errors.full_messages.each do |message| %>

    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<br>
<%= f.label :title %>
<br>
<%= f.text_field :title %>
<br>
<%= f.label :description %>
<br>
<%= f.text_field :description %>
<br>
<%= f.label :link %>
<br>
<%= f.text_field :link %>
<br>
<%= f.fields_for :user_link do |l| %>
 <%= l.label "Enter 1-3 as the number of weeks you'd like your link available for." %>
 <br>
 <%= l.number_field :expiration %><br>
<% end %>
<br>
<%= f.submit "Submit Link" %>
<% end %>

app/views/links/show.html.erb
<br>
<a href="<%=@link.link%>" target="_blank"><%= @link.title %></a>
<br>
<%= @link.description %>
<br>
<% if @user_link != nil %>
<h3>This link will expire on <%=@user_link.expiration_date%>. <%=@user_link.time_left%></h3>
<br>
<%= link_to("Mark this link read.", user_link_path(@user_link), :data => { :confirm => "Are you sure you read it?" }, :method => :delete, :class => 'button-xs')%>
<% end %>