config/routes.rb
Rails.application.routes.draw do
  # get 'user/show'

  get 'static/home'
  root 'static#home'

  # get 'users/:user_id/links/:id', to: 'links#show'

  resources :list_tasks
  resources :tasks
  resources :lists
  resources :user_videos
  resources :videos
  resources :user_links
  resources :links
  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :links
  end

  resources :users do
    resources :lists
  end

  resources :users do
    resources :videos
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hourglass</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
          <li><%= link_to 'Your homepage', '/' %></li>
          <li><%= link_to "All videos", videos_path %></li>
          <li><%= link_to "All links", links_path %></li>
          <% else %>
          <h2>HourGlass</h2>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<br>
<br>
<br>


    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
    <br>
    <br>
    <%= yield %>
  </body>
</html>